#############################################################################
# Makefile for building: bin/Resizer+
# Generated by qmake (2.01a) (Qt 4.4.3) on: vie oct 16 20:17:40 2009
# Project:  Resizer+.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile Resizer+.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Icompilar -Icompilar
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = compilar/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindowimpl.cpp \
		src/resizer_lib.cpp \
		src/infoimpl.cpp compilar/moc_mainwindowimpl.cpp \
		compilar/moc_infoimpl.cpp
OBJECTS       = compilar/main.o \
		compilar/mainwindowimpl.o \
		compilar/resizer_lib.o \
		compilar/infoimpl.o \
		compilar/moc_mainwindowimpl.o \
		compilar/moc_infoimpl.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Resizer+.pro
QMAKE_TARGET  = Resizer+
DESTDIR       = bin/
TARGET        = bin/Resizer+

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): compilar/ui_mainwindow.h compilar/ui_info.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Resizer+.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Resizer+.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Resizer+.pro

dist: 
	@$(CHK_DIR_EXISTS) compilar/Resizer+1.0.0 || $(MKDIR) compilar/Resizer+1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) compilar/Resizer+1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.h src/resizer_lib.h src/infoimpl.h compilar/Resizer+1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindowimpl.cpp src/resizer_lib.cpp src/infoimpl.cpp compilar/Resizer+1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/info.ui compilar/Resizer+1.0.0/ && (cd `dirname compilar/Resizer+1.0.0` && $(TAR) Resizer+1.0.0.tar Resizer+1.0.0 && $(COMPRESS) Resizer+1.0.0.tar) && $(MOVE) `dirname compilar/Resizer+1.0.0`/Resizer+1.0.0.tar.gz . && $(DEL_FILE) -r compilar/Resizer+1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: compilar/moc_mainwindowimpl.cpp compilar/moc_infoimpl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) compilar/moc_mainwindowimpl.cpp compilar/moc_infoimpl.cpp
compilar/moc_mainwindowimpl.cpp: compilar/ui_mainwindow.h \
		src/infoimpl.h \
		compilar/ui_info.h \
		src/resizer_lib.h \
		src/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o compilar/moc_mainwindowimpl.cpp

compilar/moc_infoimpl.cpp: compilar/ui_info.h \
		src/infoimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/infoimpl.h -o compilar/moc_infoimpl.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: compilar/ui_mainwindow.h compilar/ui_info.h
compiler_uic_clean:
	-$(DEL_FILE) compilar/ui_mainwindow.h compilar/ui_info.h
compilar/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o compilar/ui_mainwindow.h

compilar/ui_info.h: ui/info.ui
	/usr/bin/uic-qt4 ui/info.ui -o compilar/ui_info.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

compilar/main.o: src/main.cpp src/mainwindowimpl.h \
		compilar/ui_mainwindow.h \
		src/infoimpl.h \
		compilar/ui_info.h \
		src/resizer_lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilar/main.o src/main.cpp

compilar/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		compilar/ui_mainwindow.h \
		src/infoimpl.h \
		compilar/ui_info.h \
		src/resizer_lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilar/mainwindowimpl.o src/mainwindowimpl.cpp

compilar/resizer_lib.o: src/resizer_lib.cpp src/resizer_lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilar/resizer_lib.o src/resizer_lib.cpp

compilar/infoimpl.o: src/infoimpl.cpp src/infoimpl.h \
		compilar/ui_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilar/infoimpl.o src/infoimpl.cpp

compilar/moc_mainwindowimpl.o: compilar/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilar/moc_mainwindowimpl.o compilar/moc_mainwindowimpl.cpp

compilar/moc_infoimpl.o: compilar/moc_infoimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilar/moc_infoimpl.o compilar/moc_infoimpl.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

